#!/usr/bin/env python3
"""God Code interpreter benchmark suite.

Drives the real interpreter (direct import of the godcode package, no
subprocess) over representative workloads and reports the median of
several timed runs. Every workload scroll is generated deterministically,
written to bench/scrolls/, and validated with `godcode check` before any
timing begins.

Usage:
    python3 bench/bench.py                 # full run
    python3 bench/bench.py --quick         # short smoke run
    python3 bench/bench.py --json out.json # also write machine-readable results
    python3 bench/bench.py --only fib_recursion
    python3 bench/bench.py --runs 7 --warmups 3

Methodology notes (also in bench/README.md):
  * warmup runs execute each workload before timing starts,
  * each benchmark is timed N times and the MEDIAN is reported,
  * the Python random seed is fixed (workloads use their own Random(SEED)),
  * interpreter runs use log_path=None (the per-statement session log is
    disabled so the numbers measure the interpreter, not disk logging),
    REVEAL output is captured to a null sink, and plugins are disabled
    (GODCODE_NO_PLUGINS=1),
  * a fresh Interpreter is built for every timed run,
  * machine info (platform, Python, CPU) is captured with the results.
"""

from __future__ import annotations

import argparse
import contextlib
import io
import json
import os
import platform
import random
import statistics
import subprocess
import sys
import tempfile
import time
from dataclasses import dataclass, field
from pathlib import Path

REPO_ROOT = Path(__file__).resolve().parent.parent
SCROLLS_DIR = Path(__file__).resolve().parent / "scrolls"
sys.path.insert(0, str(REPO_ROOT))
os.environ.setdefault("GODCODE_NO_PLUGINS", "1")

from godcode import __version__ as GODCODE_VERSION  # noqa: E402
from godcode import chain as chain_module  # noqa: E402
from godcode.interpreter import Interpreter  # noqa: E402
from godcode.lexer import Lexer  # noqa: E402
from godcode.parser import Parser  # noqa: E402

SEED = 20260925
NULL_SINK = lambda line: None  # noqa: E731


class BenchError(RuntimeError):
    """A workload failed validation or execution."""


# ------------------------------------------------------------------ machine


def cpu_info() -> str:
    try:
        with open("/proc/cpuinfo", encoding="utf-8") as handle:
            for line in handle:
                if line.startswith("model name"):
                    return line.split(":", 1)[1].strip()
    except OSError:
        pass
    return platform.processor() or platform.machine() or "unknown"


def machine_info() -> dict:
    return {
        "godcode_version": GODCODE_VERSION,
        "python": platform.python_version(),
        "platform": platform.platform(),
        "cpu": cpu_info(),
    }


# ------------------------------------------------------------- scroll builds

_BIG_NAMES = ["grace", "peace", "mercy", "light", "hope", "faith", "joy", "love"]


def build_big_scroll(units: int, rng: random.Random) -> str:
    """A large generated scroll exercising DECLARE, interpolation, IF blocks,
    rites, and invocations. Used for the lex+parse benchmark."""
    lines = [
        "# Generated by bench/bench.py. DO NOT EDIT.",
        "# A large scroll for measuring lexing and parsing.",
        "BEGIN CREATION",
    ]
    for k in range(units):
        name = _BIG_NAMES[k % len(_BIG_NAMES)]
        var = f"{name}_{k}"
        lines.append(f"  DECLARE {var} AS {k} * 2 + {k % 7}")
        lines.append(f'  REVEAL("blessing {{{var}}} upon the house of {name}")')
        if k % 5 == 0:
            lines.append(f"  IF {var} IS {var} THEN")
            lines.append(f'    REVEAL("sealed {k}")')
            lines.append("  ENDIF")
        if k % 25 == 0:
            lines.append(f"  DEFINE RITE rite_{k}(x)")
            lines.append(f"    RETURN x + {k}")
            lines.append("  END RITE")
            lines.append(f"  INVOKE rite_{k}({k})")
    lines.append("END CREATION")
    return "\n".join(lines) + "\n"


def build_fib(n: int) -> str:
    return f"""# Recursive fibonacci. Depth stays at {n}, well inside the call stack.
BEGIN CREATION
  DEFINE RITE fib(n)
    IF n < 2 THEN
      RETURN n
    ENDIF
    RETURN fib(n - 1) + fib(n - 2)
  END RITE
  REVEAL(fib({n}))
END CREATION
"""


def build_while_loop(count: int) -> str:
    return f"""# A tight counting WHILE loop.
BEGIN CREATION
  DECLARE total AS 0
  DECLARE i AS 0
  WHILE i < {count} DO
    DECLARE total AS total + i
    DECLARE i AS i + 1
  ENDWHILE
  REVEAL(total)
END CREATION
"""


def build_interp(count: int) -> str:
    return f"""# String interpolation: REVEAL with several breathed-in expressions.
BEGIN CREATION
  DECLARE name AS "seeker"
  DECLARE i AS 0
  WHILE i < {count} DO
    REVEAL("blessing {{i}} upon {{name}}, doubled is {{i * 2}}, shouted {{UPPER(name)}}")
    DECLARE i AS i + 1
  ENDWHILE
END CREATION
""".replace("{{", "{").replace("}}", "}")


def build_lists(count: int) -> str:
    return f"""# List work: PUSH a list together, then iterate and sum it.
BEGIN CREATION
  DECLARE xs AS []
  DECLARE i AS 0
  WHILE i < {count} DO
    DECLARE xs AS PUSH(xs, i * 3)
    DECLARE i AS i + 1
  ENDWHILE
  DECLARE total AS 0
  FOR x IN xs
    DECLARE total AS total + x
  ENDFOR
  REVEAL(total)
END CREATION
"""


def build_json(round_trips: int) -> str:
    return f"""# JSON encode/decode round trips through the real registry scroll
# json-tools (IMPORT runs the actual scroll shipped in registry/scrolls).
BEGIN CREATION
  IMPORT "../../registry/scrolls/json-tools/1.0.0/json-tools.god"
  DECLARE record AS ["alakanani", 48, true, ["grace", "peace"]]
  DECLARE i AS 0
  WHILE i < {round_trips} DO
    DECLARE text AS JSON_ENCODE(record)
    DECLARE back AS JSON_DECODE(text)
    DECLARE i AS i + 1
  ENDWHILE
  REVEAL(JSON_ENCODE(record))
END CREATION
"""


def build_anchor(seals: int) -> str:
    return f"""# ANCHOR several values on the simulated chain: hashing plus the
# tamper-evident JSONL chain append per seal.
BEGIN CREATION
  DECLARE i AS 0
  WHILE i < {seals} DO
    ANCHOR("seal of blessing number " + STR(i))
    DECLARE i AS i + 1
  ENDWHILE
  REVEAL("anchored {seals} seals")
END CREATION
"""


# -------------------------------------------------------------- benchmarks


@dataclass
class Benchmark:
    name: str
    title: str
    unit: str
    detail: str
    kind: str  # "lexparse" or "exec"
    source: str = ""
    scroll_path: Path = field(default_factory=Path)
    factory_note: str = ""


def define_benchmarks(quick: bool) -> list[Benchmark]:
    rng = random.Random(SEED)
    if quick:
        sizes = dict(big=500, fib=16, loop=5000, interp=500, lists=1000,
                     json=10, anchor=10)
    else:
        sizes = dict(big=3000, fib=22, loop=20000, interp=2000, lists=5000,
                     json=50, anchor=50)
    src_big = build_big_scroll(sizes["big"], rng)
    return [
        Benchmark(
            name="lex_parse", title="Lex + parse, large scroll", unit="ms",
            kind="lexparse", source=src_big,
            detail=f"{src_big.count(chr(10))} lines, "
                   f"{len(src_big) / 1024:.1f} KB generated scroll",
        ),
        Benchmark(
            name="fib_recursion", title="Deep recursion (fib)",
            unit="ms", kind="exec", source=build_fib(sizes["fib"]),
            detail=f"fib({sizes['fib']}) by naive double recursion",
        ),
        Benchmark(
            name="while_loop", title="Tight WHILE loop", unit="ms",
            kind="exec", source=build_while_loop(sizes["loop"]),
            detail=f"counting loop of {sizes['loop']} iterations",
        ),
        Benchmark(
            name="string_interp", title="String interpolation", unit="ms",
            kind="exec", source=build_interp(sizes["interp"]),
            detail=f"{sizes['interp']} REVEALs with breathed-in expressions",
        ),
        Benchmark(
            name="list_ops", title="List build and iterate", unit="ms",
            kind="exec", source=build_lists(sizes["lists"]),
            detail=f"PUSH {sizes['lists']} items, then FOR-sum them",
        ),
        Benchmark(
            name="json_stdlib", title="JSON stdlib round-trip", unit="ms",
            kind="exec", source=build_json(sizes["json"]),
            detail=f"{sizes['json']} JSON_ENCODE/JSON_DECODE round trips "
                   "through the registry json-tools scroll",
        ),
        Benchmark(
            name="anchor_chain", title="ANCHOR chain sealing", unit="ms",
            kind="exec", source=build_anchor(sizes["anchor"]),
            detail=f"{sizes['anchor']} ANCHOR seals on a fresh simulated chain",
        ),
    ]


def check_scroll(path: Path) -> None:
    """Validate a workload scroll with the real `godcode check` CLI."""
    proc = subprocess.run(
        [sys.executable, "-m", "godcode", "check", str(path)],
        cwd=REPO_ROOT, capture_output=True, text=True,
    )
    if proc.returncode != 0:
        raise BenchError(
            f"godcode check failed for {path.name}:\n{proc.stdout}{proc.stderr}"
        )


def make_interpreter(bench: Benchmark) -> Interpreter:
    if bench.name == "anchor_chain":
        tmp = tempfile.mkdtemp(prefix="godcode-bench-chain-")
        adapters = {
            "simulated": chain_module.SimulatedChainAdapter(
                path=str(Path(tmp) / "anchors.chain")
            )
        }
        interp = Interpreter(log_path=None, chain_adapters=adapters)
    else:
        interp = Interpreter(log_path=None)
    interp.emit = NULL_SINK
    return interp


def time_lexparse(source: str, warmups: int, runs: int) -> list[float]:
    for _ in range(warmups):
        Parser(Lexer(source).lex()).parse()
    times = []
    for _ in range(runs):
        start = time.perf_counter()
        Parser(Lexer(source).lex()).parse()
        times.append((time.perf_counter() - start) * 1000.0)
    return times


def time_exec(bench: Benchmark, warmups: int, runs: int) -> list[float]:
    try:
        program = Parser(Lexer(bench.source).lex()).parse()
    except Exception as exc:  # noqa: BLE001 - report as a bench failure
        raise BenchError(f"could not parse {bench.name}: {exc}") from exc
    source_name = str(bench.scroll_path)
    times = []
    with contextlib.redirect_stdout(io.StringIO()):
        for iteration in range(warmups + runs):
            interp = make_interpreter(bench)
            start = time.perf_counter()
            try:
                interp.run(program, source_name=source_name)
            except Exception as exc:  # noqa: BLE001
                phase = "warmup" if iteration < warmups else "timed run"
                raise BenchError(
                    f"workload {bench.name} failed during {phase}: {exc}"
                ) from exc
            elapsed = (time.perf_counter() - start) * 1000.0
            if iteration >= warmups:
                times.append(elapsed)
    return times


# ------------------------------------------------------------------ driver


def run_all(quick: bool, warmups: int, runs: int,
            only: str | None) -> tuple[list[dict], dict]:
    random.seed(SEED)
    SCROLLS_DIR.mkdir(parents=True, exist_ok=True)
    benchmarks = define_benchmarks(quick)
    if only:
        benchmarks = [b for b in benchmarks if b.name == only]
        if not benchmarks:
            raise BenchError(f"unknown benchmark: {only}")

    print(f"# validating {len(benchmarks)} workload scroll(s) "
          f"with godcode check", file=sys.stderr)
    for bench in benchmarks:
        bench.scroll_path = SCROLLS_DIR / f"{bench.name}.god"
        bench.scroll_path.write_text(bench.source, encoding="utf-8")
        check_scroll(bench.scroll_path)

    results = []
    for bench in benchmarks:
        print(f"# running {bench.name} "
              f"({warmups} warmup + {runs} timed)", file=sys.stderr)
        if bench.kind == "lexparse":
            times = time_lexparse(bench.source, warmups, runs)
        else:
            times = time_exec(bench, warmups, runs)
        results.append({
            "name": bench.name,
            "title": bench.title,
            "unit": bench.unit,
            "detail": bench.detail,
            "median_ms": statistics.median(times),
            "min_ms": min(times),
            "max_ms": max(times),
            "runs": runs,
            "warmups": warmups,
        })
    meta = machine_info()
    meta.update({
        "seed": SEED, "mode": "quick" if quick else "full",
        "runs": runs, "warmups": warmups,
    })
    return results, meta


def print_table(results: list[dict], meta: dict) -> None:
    print(f"God Code interpreter benchmarks (godcode {meta['godcode_version']})")
    print(f"Python {meta['python']} on {meta['platform']}")
    print(f"CPU: {meta['cpu']}")
    print(f"Mode: {meta['mode']}, seed {meta['seed']}, "
          f"{meta['warmups']} warmup + {meta['runs']} timed runs, median shown")
    print()
    print("benchmark | median_ms | min_ms | max_ms | runs | detail")
    for row in results:
        print(f"{row['name']} | {row['median_ms']:.1f} | "
              f"{row['min_ms']:.1f} | {row['max_ms']:.1f} | "
              f"{row['runs']} | {row['detail']}")


def main(argv: list[str] | None = None) -> int:
    parser = argparse.ArgumentParser(
        description="Benchmark the God Code interpreter. "
                    "Workload scrolls are generated, validated with "
                    "godcode check, then timed; the median of the timed "
                    "runs is reported."
    )
    parser.add_argument("--quick", action="store_true",
                        help="short smoke run: smaller workloads, "
                             "1 warmup and 3 timed runs")
    parser.add_argument("--json", metavar="PATH", default=None,
                        help="also write machine-readable results to PATH")
    parser.add_argument("--runs", type=int, default=None,
                        help="timed runs per benchmark (default 5, "
                             "3 with --quick)")
    parser.add_argument("--warmups", type=int, default=None,
                        help="warmup runs per benchmark (default 2, "
                             "1 with --quick)")
    parser.add_argument("--only", metavar="NAME", default=None,
                        help="run a single benchmark by name")
    args = parser.parse_args(argv)

    quick = args.quick
    runs = args.runs if args.runs is not None else (3 if quick else 5)
    warmups = args.warmups if args.warmups is not None else (1 if quick else 2)

    try:
        results, meta = run_all(quick, warmups, runs, args.only)
    except BenchError as exc:
        print(f"bench failed: {exc}", file=sys.stderr)
        return 1

    print_table(results, meta)
    if args.json:
        out = {"tool": "godcode-bench", "meta": meta, "results": results}
        Path(args.json).write_text(json.dumps(out, indent=2), encoding="utf-8")
        print(f"\nwrote {args.json}", file=sys.stderr)
    return 0


if __name__ == "__main__":
    sys.exit(main())
