# The Scroll of Lots -- discerning choice by sacred chance.
# Rites: PROPHESY_NUMBER, CAST_LOTS, CHOOSE.

DEFINE RITE PROPHESY_NUMBER(n)
RETURN RANDOM(n)
END RITE

DEFINE RITE CAST_LOTS()
RETURN RANDOM(2)
END RITE

DEFINE RITE CHOOSE(xs)
RETURN xs[RANDOM(LEN(xs))]
END RITE
