# The Scroll of Multitudes -- reckonings over gathered lists.
# Rites: SUM, AVG, CONTAINS, SECOND, TAIL, COUNT.

DEFINE RITE SUM(xs)
DECLARE total AS 0
DECLARE i AS 0
WHILE i < LEN(xs) DO
DECLARE total AS total + xs[i]
DECLARE i AS i + 1
ENDWHILE
RETURN total
END RITE

DEFINE RITE AVG(xs)
RETURN SUM(xs) / LEN(xs)
END RITE

DEFINE RITE CONTAINS(xs, x)
DECLARE i AS 0
WHILE i < LEN(xs) DO
IF xs[i] IS x THEN
RETURN 1
ENDIF
DECLARE i AS i + 1
ENDWHILE
RETURN 0
END RITE

DEFINE RITE SECOND(xs)
RETURN xs[1]
END RITE

DEFINE RITE TAIL(xs)
DECLARE tail AS []
DECLARE i AS 1
WHILE i < LEN(xs) DO
DECLARE tail AS PUSH(tail, xs[i])
DECLARE i AS i + 1
ENDWHILE
RETURN tail
END RITE

DEFINE RITE COUNT(xs, x)
DECLARE n AS 0
DECLARE i AS 0
WHILE i < LEN(xs) DO
IF xs[i] IS x THEN
DECLARE n AS n + 1
ENDIF
DECLARE i AS i + 1
ENDWHILE
RETURN n
END RITE
